### PR TITLE
Feature/proxied caller config

### PR DESCRIPTION
**Pull request by amilor**
I have added configuration option called **proxiedCaller**, if this option is set to true then the caller information is resolved with an offset of +1. 

This is useful when using an abstraction over the `NGXLogger` such as a custom `LoggerService`, that uses an injected `NGXLogger`. In this scenario the caller information would always point to the `LoggerService` file, which is not very useful. With **proxiedCaller: true** configuration the caller information will be resolved to that which is calling the `LoggerService` and not the `NGXLogger`.

**Default value of `undefined` does not change the current behavior, user must opt-in with a value of `true` to enable the new behavior.**

### CODE REVIEW

**Review by qortex — DISMISSED** [review]
Thanks for the PR!

I think it would be a nice addition. It would make sense to let the user choose how many steps should be skipped (in the PR, it is assumed this number is always `1`).

Could you update the PR to a `proxiedSteps: number` and use that number instead of the `boolean`?

**Comment by bmtheo** [comment]
@qortex I just updated the PR so that we have a number instead of a boolean, also added a comment on the config

**Comment by EbvcRM** [comment]
Can this PR be merged in @qortex ? it looks like @bmtheo addressed the change request and this would be really helpful. Cheers

**Review by dbfannin — APPROVED** [review]

**Comment by qortex** [comment]
sorry guys, slept on the job!

**Comment by EbvcRM** [comment]
Thanks for sorting 👍

**Pull request merged**
