### PR TITLE
Change Trace log color from Blue to Purple for readability on Dark Theme #188

### PR DESCRIPTION
**Pull request by maroy1986**
As per #188, here's the PR to change the `Trace` log color for the timestamp so it gets more readable when using the dark theme in DevTools. I went with purple instead of blue. This color proves to be readable either in light or dark theme.

Here's a preview of it :

After :
image

Before :
image

As well as what it looks like on Light Theme with purple :
image

Thanks for your time!

### CODE REVIEW

**Comment by qortex** [comment]
Thanks for the PR!

I'm wondering if we could improve this further by making the color configurable through the config object. People might want their own custom coloring to match whatever they are used to. In my case, I would see value in matching my backend logging color patterns.

**Comment by dbfannin** [comment]
@qortex That's an interesting idea. What if we provide different color schemes that a user could choose from. that way it would make it very easy to adopt this feature. 

If this didn't solve the problem, we could additionally allow a user to create a custom color scheme, but I think for the first pass we should make it as simple as possible to adopt the new feature

**Comment by maroy1986** [comment]
All these ideas sound great! I like it! I can probably extend my PR with that or create another one specific for that, depending on how you want to handle that.

But I think configurable colors could definitely be a great addition!

**Comment by dbfannin** [comment]
@maroy1986, we discussed it with a few. of the other contributors, and we liked the idea of providing a color scheme, which would just be an array of colors. 

- the index matching up to the log level. So it would be an array with 7 items. 
- This would be passed into the config
- It would default to the default color scheme
- users can create their own color schemes and pass it into the config

If you want to tackle it, you can update this PR with that work!

**Comment by maroy1986** [comment]
@dbfannin I'll have a look at it in the next few days, I'll keep you posted!

**Comment by maroy1986** [comment]
@dbfannin Here you go! I implemented the changes based on your last post.

One thing I didn't do was adding a way to configure and try them in the demo app. Is this something that would be valuable?

**Comment by maroy1986** [comment]
> Thanks for writing unit tests for this feature! It looks good!

We should always write unit test :) Thanks for merging!

**Pull request merged**
