### PR TITLE
avoids fail on complex structure when logging

### LINKED ISSUE #177: Cannot log FormGroup with innner FormGroup
Hi,

When I try to log a FormGroup instance like I usually do it with `console.log`, it returns me:
`The provided "message" value could not be parsed with JSON.stringify().`

After some tests:
`this.logger.info(new FormGroup({}));` is OK
`this.logger.info(new FormGroup({ sub: new FormGroup({}) }));` is KO

I guess this is some circular link between both FormGroups.

How can I avoid this?

Thx.

### PR DESCRIPTION
**Pull request by bmtheo**
fix #177 by removing the prepareMessage (JSON.stringify) call when logging
The prepareMessage call is still needed for server logging thus complex structure don't working with server logging

### CODE REVIEW

**Review by dbfannin — APPROVED** [review]

**Comment by qortex** [comment]
Still not sure what this change achieves really. What am I missing?

**Comment by bmtheo** [comment]
this avoid any fail related to the JSON.stringify call, the console.log do not use it and and it can log "complex structure" without any trouble
Example : `this.logger.info(new FormGroup({ sub: new FormGroup({}) }));`

The JSON.stringify is still used for server logging

I'm gonna look into this conflict to fix it

**Review by qortex — APPROVED** [review]
ok

**Comment by qortex** [comment]
Ok yes, misread the code and thought the change did not achieve that.

**Pull request merged**
