### PR TITLE
Angular 5 Support

### PR DESCRIPTION
**Pull request by IsNull**
* Updated dependencies
* Removed deprecated (and unused) `@angular/http` dependency
* Committed lock file to ensure reproducible builds
* Fixed missing jasmine import in spec

### CODE REVIEW

**Comment by IsNull** [comment]
Depending on your plans, we could also try to allow the 4.x Angular in the peer dependencies. 
It should be compatible, as long no special features of angular or Rx (read: lettable operators) are used.

**Comment by dbfannin** [comment]
can we update the version to 2.0.0 in both package.json files? That way, we won't break anyone using a version of 4.x.

**Comment by IsNull** [comment]
Yes we should absolutely raise a major version to avoid breaking stuff.

The way I usually handle this in my libraries is that I merge in the stuff from other people into master, and raise the version on the master branch directly. 

How do you want to handle this?

Btw: I would remove the version from the outer package.json as it has no purpose. Only the one in src is exposed in public. I usually remove the library name from the outer aswell, as it is just confusing. I.e. [outer package.json](https://github.com/ElderByte-/ngx-starter/blob/master/package.json) and the [inner](https://github.com/ElderByte-/ngx-starter/blob/master/src/package.json) with the info.

**Comment by IsNull** [comment]
Btw, you could consider adopting the versioning from Angular Material for ngx libraries:

Specifically, the major version is linked to the Angular version. So the version would be `5.x.x` for the Angular 5 branch.

**Pull request merged**
