### PR TITLE
Refactoring build system to use v6 library build configuration

### PR DESCRIPTION
**Pull request by leo6104**
- rename types/logger-lever.enum.ts -> types/logger-level.enum.ts
- create ng-package.json & angular.json file for ng-packagr build (ng6)
- remove gulpfile & gulp related dependency
- remove build:watch npm command (ng6 not support yet)
- rxjs import to 'rxjs' (webpack 4 & angular 6 way)
- compodoc problem @return,@private annotations must be written with two space (typescript compilation failed - https://github.com/Microsoft/TypeScript/issues/9694)
- second entrypoint `ngx-logger/testing` for mock files.

issue #53 Can you have a look this commit? @dbfannin 

**What we have to do**
- [x] Separate test code from src folder. (exclude mock.ts, test code from build output)
- [x] this release version must be start with RC release. this PR might be breaking changes.

### CODE REVIEW

**Comment by dbfannin** [comment]
@leo6104, since @angular/cli v6 supports libraries directly. I want to use @angular/cli for the build system of ngx-logger instead a project like ng-packagr or angular2-library.

**Comment by leo6104** [comment]
@dbfannin I read your comment. This PR use v6's library configuration. v6 library internally use ng-packagr. 
https://github.com/dbfannin/ngx-logger/pull/59/files

**Comment by dbfannin** [comment]
Sorry, @leo6104! When I read the title I assumed you used ng-packagr directly. I wanted to make sure we used @angular/cli so we could easily take advantage of their updates. I've re-opened this PR. I'm going to wait to approve and squash/merge, until angular 6 stable is release.

Thanks for all the hard work!

**Comment by leo6104** [comment]
### Today's updates
- remove invalid LICENSE file (ng build - copying assets not working yet)
- remove unused dependency `node-sass, node-sass-tilde-importer, node-watch`
- update `rxjs, ts-node, tslint, ng-packagr, karma` to latest
- remove tsc command on npm run test (no need anymore)
- remove --type-check deprecated option in tslint command 

@dbfannin Can you setup Travis CI for this repository? Public git repository can use Travis CI as free. I cannot setup Travis CI setup in ngx-logger main repository. It only available to owned repository.

**Comment by leo6104** [comment]
Rebase to master. https://github.com/dbfannin/ngx-logger/network

**Comment by leo6104** [comment]
I suggest second entrypoint `ngx-logger/testing` for mock file. 

Actually, there is no need to include mock.ts files when we imports `ngx-logger` because we compile angular project to browser target (not test build). Mock files is only used in spec files.
So, we need to provide separate entry point `ngx-logger/testing` for mock files. 

As we provides second entrypoint `ngx-logger/testing`, we could exclude mock.ts files in browser target compilation. 

@dbfannin Please comment for https://github.com/dbfannin/ngx-logger/pull/59/commits/5aa15421e7034cd3fa733f61313cb4c93994cedb commit. :)

**Comment by dbfannin** [comment]
@leo6104, right, there is no need to create a module here, but I like the idea of creating this entrypoint as an access to all mocks. Sounds good!

**Comment by dbfannin** [comment]
@leo6104, is this ready to be merged? we've had a request to create our own RC for angular6 support (#63). If it's good to go, then I can go ahead and publish a RC for it. I wasn't sure if you were still working on same changes around the testing entrypoint.

**Comment by leo6104** [comment]
@dbfannin Oh, it is ready to be merged. :)

**Comment by MickL** [comment]
Yes please create RC for use with Angular 6. The earlier you release that the earlier you might get feedback on possible bugs :)

**Pull request merged**
