### PR TITLE
Use HttpClient instead of HttpBackend when withCredentials is true in…

### PR DESCRIPTION
**Pull request by naris**
Issue #130 Added withCredentials to the config and to NGXLoggerServerService.logOnServer<T>(). However it doesn't actually do anything :(

This updates NGXLoggerServerService.logOnServer<T>() to use HttpClient instead of HttpBackend for the request, if withCredentials is true, so that http interceptors are invoked in order to add any required Authentication headers or whatever else.

### CODE REVIEW

**Comment by bmtheo** [comment]
withCredentials should be working fine, do you have a bug ?

It is sent in the function sendToServer line 130
And then the options object is provided to the request object in this line (line 88):
```
    const req = new HttpRequest<T>('POST', url, logContent, options || {});
```

sendToServer function:
```
  public sendToServer(metadata: INGXLoggerMetadata, config: INGXLoggerConfig): void {
    // Copying metadata locally because we don't want to change the object for the caller
    const localMetadata = { ...metadata };

    localMetadata.additional = this.secureAdditionalParameters(localMetadata.additional);

    localMetadata.message = this.secureMessage(metadata.message);

    // Allow users to customise the data sent to the API
    const requestBody = this.customiseRequestBody(metadata);

    const headers = config.customHttpHeaders || new HttpHeaders();
    if (!headers.has('Content-Type')) {
      headers.set('Content-Type', 'application/json');
    }

    this.logOnServer<any>(config.serverLoggingUrl, requestBody, {
      headers,
      params: config.customHttpParams || new HttpParams(),
      responseType: config.httpResponseType || 'json',
      withCredentials: config.withCredentials || false, // <---------------------------- HERE
    }).pipe(catchError(err => {
      // Do not use NGXLogger here because this could cause an infinite loop 
      console.error('NGXLogger: Failed to log on server', err);
      return throwError(err);
    })).subscribe();
  }
```

**Comment by naris** [comment]
> withCredentials should be working fine, do you have a bug ?
> 
> It is sent in the function sendToServer line 130 And then the options object is provided to the request object in this line (line 88):
> 
> ```
>     const req = new HttpRequest<T>('POST', url, logContent, options || {});
> ```
> 
> sendToServer function:
> 
> ```
>   public sendToServer(metadata: INGXLoggerMetadata, config: INGXLoggerConfig): void {
>     // Copying metadata locally because we don't want to change the object for the caller
>     const localMetadata = { ...metadata };
> 
>     localMetadata.additional = this.secureAdditionalParameters(localMetadata.additional);
> 
>     localMetadata.message = this.secureMessage(metadata.message);
> 
>     // Allow users to customise the data sent to the API
>     const requestBody = this.customiseRequestBody(metadata);
> 
>     const headers = config.customHttpHeaders || new HttpHeaders();
>     if (!headers.has('Content-Type')) {
>       headers.set('Content-Type', 'application/json');
>     }
> 
>     this.logOnServer<any>(config.serverLoggingUrl, requestBody, {
>       headers,
>       params: config.customHttpParams || new HttpParams(),
>       responseType: config.httpResponseType || 'json',
>       withCredentials: config.withCredentials || false, // <---------------------------- HERE
>     }).pipe(catchError(err => {
>       // Do not use NGXLogger here because this could cause an infinite loop 
>       console.error('NGXLogger: Failed to log on server', err);
>       return throwError(err);
>     })).subscribe();
>   }
> ```
Yeah, as I stated withCredentials  doesn't effectively do anything.. The only thing it does is to set a value (withCredentials) that is not actually used by the code anywhere, the code in logOnServer() does not use withCredentials at all -- it is passed in but not used. Setting it has no effect whatsoever. What is the point of that?

The patch I submitted changes logOnServer() to use the withCredentials as a flag to use the HttpClient.request() instead of HttpBackend.handle() soo that the rerquest will get handled by any interceptors which can then add Authorization (or anything else).

**Comment by bmtheo** [comment]
withCredentials is a property of the options object used by HttpRequest, see doc here https://angular.io/api/common/http/HttpRequest

You are mixing up withCredentials options and using HttpClient (so that Interceptors are used etc...)

HttpClient is not used on purpose to avoid any infinite loop (if you log anything in your interceptor for example)

However if you want to use HttpClient yourself you need to customise log behavior (doc here : https://github.com/dbfannin/ngx-logger/blob/master/docs/customising.md), ask me if you need help for that

**Comment by naris** [comment]
Oh, Obviously I didn't realize that withCredentials was an option of HttpRequest. I have reworked my code to be a separate class extending NGXLoggerServerService. I'll submit that as another pull request as there seems to be a lot of interest in it and a lot of people need a solution for calling authenticated backed services (and having a solution "in the box" without requiring additional coding would be helpful for them)

**Comment by naris** [comment]
I created #276 "Add NGXLoggerInterceptableServerService class for using authenticated servers" for the new code

**Pull request closed without merging**
